# Generated by Django 4.1.5 on 2023-01-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_de_la_province', models.CharField(help_text='taper le nom de la province', max_length=20, unique=True)),
            ],
        ),
    ]
