# Generated by Django 4.1.5 on 2023-01-27 07:25

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_de_la_commune', models.CharField(help_text='tapez le nom de la commune', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LevelStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_etudes', models.CharField(help_text="tapez le niveau d'études", max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatiralStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation_matrimoniale', models.CharField(help_text='renseignez la situation matrimoniale', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_de_la_province', models.CharField(help_text='taper le nom de la province', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeAide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_aide', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vulnerabilite', models.CharField(help_text='tapez le nom de la vulnerabilité', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeAssistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_assistance', models.CharField(max_length=20, unique=True)),
                ('type_aide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fondation.typeaide')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='tapez le nom de famille', max_length=30)),
                ('prenom', models.CharField(help_text='tapez le prenom', max_length=30)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'féminin')], max_length=20)),
                ('age', models.DateField(verbose_name='date de naissance')),
                ('numero_de_telephone', phone_field.models.PhoneField(blank=True, help_text='tapez le numero de téléphone', max_length=31)),
                ('nom_prenom_du_pere', models.CharField(help_text='tapez le nom et le prenom du père', max_length=50)),
                ('nom_prenom_de_la_mere', models.CharField(help_text='tapez le nom et le prenom du mère', max_length=50)),
                ('nom_de_la_zone', models.CharField(help_text="zone d'origine", max_length=20, verbose_name='zone')),
                ('nombre_enfants', models.PositiveIntegerField(help_text="renseignez le nombre d'enfants à sa charge")),
                ('fonction', models.CharField(blank=True, max_length=50)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('la_vulnerabilite', models.ForeignKey(help_text='sélectionez sa situation de vulnerabilité', on_delete=django.db.models.deletion.CASCADE, to='fondation.vulnerability')),
                ('le_niveau_etudes', models.ForeignKey(help_text="sélectionez son niveau d'études", on_delete=django.db.models.deletion.CASCADE, to='fondation.levelstudy')),
                ('nom_de_la_commune', models.ForeignKey(help_text="commune d'origine", on_delete=django.db.models.deletion.CASCADE, to='fondation.commune')),
                ('nom_de_la_province', models.ForeignKey(help_text="province d'origine", on_delete=django.db.models.deletion.CASCADE, to='fondation.province')),
                ('situation_matrimoniale', models.ForeignKey(help_text='sélectionez sa situation de situation matrimoniale', on_delete=django.db.models.deletion.CASCADE, to='fondation.matiralstatus')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_donneur', models.CharField(choices=[('org', 'Organisation'), ('entrp', 'Entreprise'), ('assoc', 'Association'), ('part', 'Particulier'), ('anonym', 'Rester anonyme')], max_length=50)),
                ('nom_du_donneur', models.CharField(blank=True, help_text="tapez votre nom / le nom de l'entreprise , de l'association ou de l'organisation", max_length=50)),
                ('numero_de_telephone', phone_field.models.PhoneField(help_text='ce numero de téléphone sera utilisé pour entrer en contact avec vous', max_length=31)),
                ('adresse_mail', models.EmailField(help_text='cette addresse mail sera utilisée pour entrer en contact avec vous', max_length=254)),
                ('description', models.TextField(blank=True, help_text='décrivez le type de don et/ou aides que vous souhaitez donner à notre fondation', max_length=500)),
                ('donor_date_given', models.DateTimeField(auto_now_add=True)),
                ('type_aide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fondation.typeaide')),
                ('type_assistance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fondation.typeassistance')),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, help_text="reseignez autre type d'assistance qui ne figure pas dans la liste", max_length=500)),
                ('date_given', models.DateTimeField(auto_now_add=True)),
                ('beneficiaire', models.ForeignKey(help_text='sélectionez le (la) bénéficiaire', on_delete=django.db.models.deletion.CASCADE, to='fondation.person', unique_for_date='date_given')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fondation.commune')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fondation.province')),
                ('type_aide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fondation.typeaide')),
                ('type_assistance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fondation.typeassistance')),
            ],
        ),
        migrations.AddField(
            model_name='commune',
            name='nom_de_la_province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fondation.province'),
        ),
        migrations.AddConstraint(
            model_name='typeassistance',
            constraint=models.UniqueConstraint(fields=('type_aide', 'type_assistance'), name='unique_type_assistance'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('nom', 'prenom', 'sexe', 'age', 'numero_de_telephone', 'nom_prenom_du_pere', 'nom_prenom_de_la_mere', 'nom_de_la_province', 'nom_de_la_commune', 'nom_de_la_zone', 'la_vulnerabilite', 'le_niveau_etudes', 'situation_matrimoniale', 'nombre_enfants', 'fonction', 'date_joined'), name='unique_person'),
        ),
        migrations.AddConstraint(
            model_name='commune',
            constraint=models.UniqueConstraint(fields=('nom_de_la_province', 'nom_de_la_commune'), name='unique_commune'),
        ),
    ]
