# Generated by Django 4.1.5 on 2023-01-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(help_text='taper le nom du province', max_length=20, unique=True, verbose_name='Nom du province')),
            ],
            options={
                'ordering': ['province_name'],
            },
        ),
    ]
