# Generated by Django 4.1.5 on 2023-01-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeaide',
            name='type_aide',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='typeassistance',
            name='type_assistance',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
