# Generated by Django 4.1.5 on 2023-01-10 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fondation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune_name', models.CharField(help_text='tapez le nom de la commune', max_length=20, unique=True, verbose_name='Nom de la commune')),
                ('province_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fondation.province')),
            ],
            options={
                'ordering': ['province_name', 'commune_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='commune',
            constraint=models.UniqueConstraint(fields=('province_name', 'commune_name'), name='unique_commune'),
        ),
    ]
