# Generated by Django 4.1.5 on 2023-01-16 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fondation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_de_la_commune', models.CharField(help_text='tapez le nom de la commune', max_length=20, unique=True)),
                ('nom_de_la_province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fondation.province')),
            ],
        ),
        migrations.AddConstraint(
            model_name='commune',
            constraint=models.UniqueConstraint(fields=('nom_de_la_province', 'nom_de_la_commune'), name='unique_commune'),
        ),
    ]
