# Generated by Django 4.1.5 on 2023-02-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondation', '0004_donor_montant_donor_montant_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='zone',
            field=models.CharField(max_length=50, verbose_name='Colline'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nom_de_la_zone',
            field=models.CharField(help_text="zone d'origine", max_length=20, verbose_name='Colline'),
        ),
    ]
