# Generated by Django 4.1.5 on 2023-02-06 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fondation', '0005_alter_distribution_zone_alter_person_nom_de_la_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='commune',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fondation.commune'),
        ),
        migrations.AddField(
            model_name='donor',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fondation.province'),
        ),
    ]
