# Generated by Django 4.1.5 on 2023-01-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondation', '0005_vulnerability'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ex : aides en nature , aides en espece', max_length=40, unique=True, verbose_name="type d'aides")),
            ],
        ),
    ]
