# Generated by Django 4.1.5 on 2023-01-13 09:07

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('fondation', '0005_vulnerability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_created=True)),
                ('nom', models.CharField(help_text='tapez le nom de famille', max_length=30)),
                ('prenom', models.CharField(help_text='tapez le prenom', max_length=30)),
                ('sexe', models.CharField(choices=[('féminin', 'Féminin')], max_length=20)),
                ('age', models.DateField()),
                ('numero_de_telephone', phone_field.models.PhoneField(blank=True, help_text='tapez le numero de téléphone', max_length=31)),
                ('nom_prenom_du_pere', models.CharField(help_text='tapez le nom et le prenom du père', max_length=50)),
                ('nom_prenom_de_la_mere', models.CharField(help_text='tapez le nom et le prenom du mère', max_length=50)),
                ('nom_de_la_zone', models.CharField(help_text="zone d'origine", max_length=20, verbose_name='zone')),
                ('nombre_enfants', models.PositiveIntegerField(help_text="renseignez le nombre d'enfants à sa charge")),
                ('fonction_avant_exil', models.CharField(blank=True, max_length=50)),
                ('la_vulnerabilite', models.ForeignKey(help_text='sélectionez sa situation de vulnerabilité', on_delete=django.db.models.deletion.CASCADE, to='fondation.vulnerability')),
                ('le_niveau_etudes', models.ForeignKey(help_text="sélectionez son niveau d'études", on_delete=django.db.models.deletion.CASCADE, to='fondation.levelstudy')),
                ('nom_de_la_commune', models.ForeignKey(help_text="commune d'origine", on_delete=django.db.models.deletion.CASCADE, to='fondation.commune')),
                ('nom_de_la_province', models.ForeignKey(help_text="province d'origine", on_delete=django.db.models.deletion.CASCADE, to='fondation.province')),
                ('situation_matrimoniale', models.ForeignKey(help_text='sélectionez sa situation de situation matrimoniale', on_delete=django.db.models.deletion.CASCADE, to='fondation.matiralstatus')),
            ],
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('nom', 'prenom', 'sexe', 'age', 'numero_de_telephone', 'nom_prenom_du_pere', 'nom_prenom_de_la_mere', 'nom_de_la_province', 'nom_de_la_commune', 'nom_de_la_zone', 'la_vulnerabilite', 'le_niveau_etudes', 'situation_matrimoniale', 'nombre_enfants', 'fonction_avant_exil', 'date_joined'), name='unique_person'),
        ),
    ]
