# Generated by Django 4.1.5 on 2023-02-06 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fondation', '0006_donor_commune_donor_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='donateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fondation.donor'),
        ),
    ]
