# Generated by Django 4.1.5 on 2023-01-13 09:22

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fondation', '0007_donation_donation_unique_donor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_given', models.DateField(auto_created=True)),
                ('type_assistance', multiselectfield.db.fields.MultiSelectField(choices=[('aide_en_nature', 'Aide en nature'), ('aide_en_espece', 'Aide en éspèce'), ('accompagnement_psychosocial', 'Accompagnement psychosocial'), ('accompagnement_medical', 'Accompagnement médical')], max_length=150)),
                ('description', models.CharField(help_text='décrivez le type de don et/ou aides que le bénéficiaire reçoit', max_length=500)),
                ('beneficiaire', models.ForeignKey(help_text='sélectionez le bénéficiaire', on_delete=django.db.models.deletion.CASCADE, to='fondation.person')),
            ],
        ),
        migrations.AddConstraint(
            model_name='distribution',
            constraint=models.UniqueConstraint(fields=('beneficiaire', 'type_assistance', 'description', 'date_given'), name='unique_distribution'),
        ),
    ]
