# Generated by Django 4.1.5 on 2023-01-11 09:15

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('fondation', '0007_help_help_unique_aide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_created=True, verbose_name="date d'arrivée")),
                ('last_name', models.CharField(help_text='tapez le nom de famille', max_length=30, verbose_name='nom de famille')),
                ('first_name', models.CharField(help_text='tapez le prenom', max_length=30, verbose_name='prenom')),
                ('gender', models.CharField(choices=[('féminin', 'Féminin')], max_length=20, verbose_name='sexe')),
                ('age', models.DateField(verbose_name='date de naissance')),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='tapez le numero de téléphone', max_length=31, verbose_name='numéro de téléphone')),
                ('father', models.CharField(help_text='tapez le nom et le prenom du père', max_length=50, verbose_name='nom et prenom du père')),
                ('mother', models.CharField(help_text='tapez le nom et le prenom du mère', max_length=50, verbose_name='nom et prenom de la mère')),
                ('zone_name', models.CharField(help_text="tapez la zone d'origine", max_length=20, verbose_name='zone')),
                ('number_of_dependent_children', models.PositiveIntegerField(verbose_name="nombre d'enfant(s) à sa charge")),
                ('work_before_exile', models.CharField(blank=True, max_length=50, verbose_name="fonction occupée avant l'exil")),
                ('commune_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fondation.commune')),
                ('level_study_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fondation.levelstudy')),
                ('matiral_status_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fondation.matiralstatus')),
                ('province_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fondation.province')),
                ('vulnerability_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fondation.vulnerability')),
            ],
            options={
                'ordering': ['-date_joined', 'last_name', 'first_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('last_name', 'first_name', 'gender', 'age', 'phone', 'father', 'mother', 'province_name', 'commune_name', 'zone_name', 'vulnerability_name', 'level_study_name', 'matiral_status_name', 'number_of_dependent_children', 'work_before_exile'), name='unique_person'),
        ),
    ]
