# Generated by Django 4.1.5 on 2023-02-07 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fondation', '0007_distribution_donateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='situation_matrimoniale',
            field=models.ForeignKey(help_text='sélectionez sa situation de situation matrimoniale', on_delete=django.db.models.deletion.CASCADE, to='fondation.matiralstatus', verbose_name='statut matrimonial'),
        ),
    ]
