# Generated by Django 4.1.5 on 2023-01-16 09:06

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fondation', '0008_donor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_given', models.DateField(auto_created=True)),
                ('type_assistance', multiselectfield.db.fields.MultiSelectField(choices=[('aide_en_nature', 'Aide en nature'), ('aide_en_espece', 'Aide en éspèce'), ('accompagnement_psychosocial', 'Accompagnement psychosocial'), ('accompagnement_medical', 'Accompagnement médical')], max_length=150)),
                ('description', models.CharField(help_text='décrivez le type de don et/ou aides que le bénéficiaire reçoit', max_length=500)),
                ('beneficiaire', models.ForeignKey(help_text='sélectionez le (la) bénéficiaire', on_delete=django.db.models.deletion.CASCADE, to='fondation.person', unique_for_date='date_given')),
                ('camp', models.ForeignKey(help_text='sélectionez le camp du refugié (e)', on_delete=django.db.models.deletion.CASCADE, to='fondation.camp')),
            ],
        ),
    ]
