# Generated by Django 4.1.5 on 2023-01-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondation', '0008_distribution_distribution_unique_distribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_du_camp', models.CharField(help_text="tapez le nom du camp d'intervetion", max_length=100, unique=True)),
                ('site', models.CharField(help_text='tapez la localisation géograpfique du camp où se trouve ce camp', max_length=100)),
            ],
        ),
        migrations.AddConstraint(
            model_name='camp',
            constraint=models.UniqueConstraint(fields=('nom_du_camp', 'site'), name='unique_camp'),
        ),
    ]
