# Generated by Django 4.1.5 on 2023-01-16 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fondation', '0009_camp_camp_unique_camp'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='person',
            name='unique_person',
        ),
        migrations.AddField(
            model_name='person',
            name='camp',
            field=models.ForeignKey(default=1, help_text='sélectionez le camp du refugié', on_delete=django.db.models.deletion.CASCADE, to='fondation.camp'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('nom', 'prenom', 'sexe', 'age', 'numero_de_telephone', 'nom_prenom_du_pere', 'nom_prenom_de_la_mere', 'camp', 'nom_de_la_province', 'nom_de_la_commune', 'nom_de_la_zone', 'la_vulnerabilite', 'le_niveau_etudes', 'situation_matrimoniale', 'nombre_enfants', 'fonction_avant_exil', 'date_joined'), name='unique_person'),
        ),
    ]
