# Generated by Django 4.1.5 on 2023-01-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondation', '0009_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='donation_received',
            field=models.BooleanField(default=0),
        ),
    ]
