# Generated by Django 4.1.5 on 2023-01-11 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fondation', '0009_donation_donation_unique_donor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-donor_date_given']},
        ),
    ]
