# Generated by Django 4.1.5 on 2023-01-19 08:25

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fondation', '0010_donor_donation_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='type_assistance',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('vivre_alimentaire', 'Vivre alimentaire'), ('ustenciles_de_cuisines', 'Ustenciles de cuisines'), ('eau_potable', 'Eau potable'), ('briquettes', 'briquettes'), ('kit_de_dignite', 'Kit de dignité pour les femmes'), ('vetements', 'Les Vêtements'), ('kit_scolaire', 'Kit Scolaire'), ('medicaments', 'Médicaments / Soins médicaux'), ('fonds_de_roulements', 'Fonds de roulements de micro-projets'), ('enseignements_de_metiers', 'Enseignements de métiers'), ('reunification_familliale', 'Réunification familliale'), ('reinstallation', 'Réinstallation'), ('kinesitherapie', 'kinésithérapie')], default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donor',
            name='description',
            field=models.CharField(blank=True, help_text='décrivez le type de don et/ou aides que vous souhaitez donner à notre fondation', max_length=500, verbose_name='Autres'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_date_given',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
