# Generated by Django 4.1.5 on 2023-01-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondation', '0010_alter_donation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-date_joined', 'first_last_name']},
        ),
        migrations.RemoveConstraint(
            model_name='person',
            name='unique_person',
        ),
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
        migrations.AddField(
            model_name='person',
            name='first_last_name',
            field=models.CharField(default=1, help_text='tapez le nom et prénom', max_length=30, verbose_name='nom et prénom'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('first_last_name', 'gender', 'age', 'phone', 'father', 'mother', 'province_name', 'commune_name', 'zone_name', 'vulnerability_name', 'level_study_name', 'matiral_status_name', 'number_of_dependent_children', 'work_before_exile'), name='unique_person'),
        ),
    ]
