# Generated by Django 4.1.5 on 2023-01-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondation', '0011_alter_person_options_remove_person_unique_person_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-date_joined', 'last_name', 'first_name']},
        ),
        migrations.RemoveConstraint(
            model_name='person',
            name='unique_person',
        ),
        migrations.RemoveField(
            model_name='person',
            name='first_last_name',
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(default=1, help_text='tapez le prenom', max_length=30, verbose_name='prenom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default=1976, help_text='tapez le nom de famille', max_length=30, verbose_name='nom de famille'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('last_name', 'first_name', 'gender', 'age', 'phone', 'father', 'mother', 'province_name', 'commune_name', 'zone_name', 'vulnerability_name', 'level_study_name', 'matiral_status_name', 'number_of_dependent_children', 'work_before_exile'), name='unique_person'),
        ),
    ]
