# Generated by Django 4.1.5 on 2023-01-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondation', '0011_alter_person_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
