# Generated by Django 4.1.5 on 2023-01-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondation', '0012_alter_person_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donor_date_given',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
