# Generated by Django 4.1.5 on 2023-01-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondation', '0013_distribution_distribution_unique_distribution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ['nom_province']},
        ),
        migrations.RemoveField(
            model_name='province',
            name='province_name',
        ),
        migrations.AddField(
            model_name='province',
            name='nom_province',
            field=models.CharField(default=1, help_text='taper le nom du province', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
