# Generated by Django 4.1.5 on 2023-01-19 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fondation', '0012_distribution_type_aide_alter_distribution_date_given_and_more'),
        ('fondation', '0015_alter_person_age'),
    ]

    operations = [
    ]
