# Generated by Django 4.1.5 on 2023-01-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondation', '0016_merge_20230119_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='description',
            field=models.CharField(blank=True, help_text="reseignez autre type d'assistance qui ne figure pas dans la liste", max_length=500, verbose_name='Autres'),
        ),
    ]
