# Generated by Django 4.1.5 on 2023-01-26 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fondation', '0018_remove_distribution_camp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='commune',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fondation.commune'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distribution',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fondation.province'),
            preserve_default=False,
        ),
    ]
