# Generated by Django 4.1.5 on 2023-01-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondation', '0019_distribution_commune_distribution_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='zone',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
