# Generated by Django 4.1.5 on 2023-01-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondation', '0021_alter_distribution_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='camp',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='donation_received',
        ),
        migrations.AlterField(
            model_name='donor',
            name='description',
            field=models.TextField(blank=True, help_text='décrivez le type de don et/ou aides que vous souhaitez donner à notre fondation', max_length=500),
        ),
        migrations.AlterField(
            model_name='donor',
            name='type_aide',
            field=models.CharField(choices=[('aide_en_nature', 'Aide en nature'), ('aide_en_espece', 'Aide en éspèce'), ('accompagnement_psychosocial', 'Accompagnement psychosocial'), ('accompagnement_medical', 'Accompagnement médical')], max_length=150),
        ),
        migrations.AlterField(
            model_name='donor',
            name='type_assistance',
            field=models.CharField(choices=[('vivre_alimentaire', 'Vivre alimentaire'), ('ustenciles_de_cuisines', 'Ustenciles de cuisines'), ('eau_potable', 'Eau potable'), ('briquettes', 'briquettes'), ('kit_de_dignite', 'Kit de dignité pour les femmes'), ('vetements', 'Les Vêtements'), ('kit_scolaire', 'Kit Scolaire'), ('medicaments', 'Médicaments / Soins médicaux'), ('fonds_de_roulements', 'Fonds de roulements de micro-projets'), ('enseignements_de_metiers', 'Enseignements de métiers'), ('reunification_familliale', 'Réunification familliale'), ('reinstallation', 'Réinstallation'), ('kinesitherapie', 'kinésithérapie')], max_length=150),
        ),
    ]
