# Generated by Django 4.1.5 on 2023-01-27 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fondation', '0023_remove_person_unique_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='beneficiaire',
            field=models.ForeignKey(default=1, help_text='sélectionez le (la) bénéficiaire', on_delete=django.db.models.deletion.CASCADE, to='fondation.person', unique_for_date='date_given'),
            preserve_default=False,
        ),
    ]
