# Generated by Django 4.1.5 on 2023-01-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondation', '0024_distribution_beneficiaire'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='person',
            name='unique_person',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='fonction_avant_exil',
            new_name='fonction',
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('nom', 'prenom', 'sexe', 'age', 'numero_de_telephone', 'nom_prenom_du_pere', 'nom_prenom_de_la_mere', 'nom_de_la_province', 'nom_de_la_commune', 'nom_de_la_zone', 'la_vulnerabilite', 'le_niveau_etudes', 'situation_matrimoniale', 'nombre_enfants', 'fonction', 'date_joined'), name='unique_person'),
        ),
    ]
