# Generated by Django 4.1.5 on 2023-01-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondation', '0025_remove_person_unique_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_aide', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Camp',
        ),
    ]
