# Generated by Django 4.1.5 on 2023-01-27 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fondation', '0026_typeaide_delete_camp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAssistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_assistance', models.CharField(max_length=20, unique=True)),
                ('type_aide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fondation.typeaide')),
            ],
        ),
        migrations.AddConstraint(
            model_name='typeassistance',
            constraint=models.UniqueConstraint(fields=('type_aide', 'type_assistance'), name='unique_type_assistance'),
        ),
    ]
